### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by tdrozdovsky**
I've fixed some inaccuracies that lead to a lot of warnings. Please check it.

### CODE REVIEW

**Comment by tdrozdovsky** [comment]
@wschang0 @yjchen5 @csyang2  Please check my pull request

**Comment by wschang0** [comment]
We had reviewed the issue but we cannot see what you mentioned about.
Could you give us more detail about your environment?

Regards,
WS

**Comment by tdrozdovsky** [comment]
@wschang0  For example ...
```
CC: portable/GCC/ARM_V8M/port.c
gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc -std=gnu99 -pipe -Wl,--gc-sections -Wall -Wextra -Wstrict-prototypes -Wshadow -Wundef -O1 -ffunction-sections -fdata-sections -mlittle-endian -mthumb -mcpu=cortex-m23 -march=armv8-m.base -Iinclude -D__ARM_FEATURE_DSP=0 -I./include -I./portable/GCC/ARM_V8M  -I./src/Device/Nuvoton/M2351/Include -I./CMSIS/Include -I./StdDriver/inc -DDEBUG_PORT=UART0_NS -c -o freertos/portable/GCC/ARM_V8M/port.o portable/GCC/ARM_V8M/port.c
In file included from ./portable/GCC/ARM_V8M/portmacro.h:58:0,
                 from ./include/portable.h:52,
                 from ./include/FreeRTOS.h:62,
                 from portable/GCC/ARM_V8M/port.c:54:
../src/Device/Nuvoton/M2351/Include/M2351.h:947:8: warning: "__ARMCC_VERSION" is not defined [-Wundef]
 #elif (__ARMCC_VERSION >= 6010050)
        ^~~~~~~~~~~~~~~
```

**Comment by tdrozdovsky** [comment]
@wschang0  P.S. The code shows that there are inaccuracies when using GCC

**Comment by wschang0** [comment]
Do you use the eclipse project of M2351 sample code?
We had try GNU C with eclipse to build the sample code and it is ok without warning.

If you still have problem, please tell us the eclipse project path of our BSP which have problem and what NuEclipse version you installed.
Thanks!

Regards,
WS

**Comment by tdrozdovsky** [comment]
@wschang0 
1. I do not use your eclipse.
2. The code in this repository differs from that used in the eclipse. (I use the code of this repository).
3. Look at this code and my PR and you can understand that there are inaccuracies here. (Please apply my PR).

P.S. Eclipse sample code also has many warnings, turn on the compiler options `-Wall -Wextra` to see them.

**Comment by tdrozdovsky** [comment]
@wschang0 
I think in any case it is necessary to correct these warnings since users download this package and I think they are not pleased to see when the compiler issues such a number of warnings

**Comment by wschang0** [comment]
As our test, we cannot find warning with our supporting tools.
However, we will modify the M2351.h for the defined of __ARMCC_VERSION
Thanks for your suggestions.


Regards,
WS

**Pull request closed without merging**
